### ISSUE TITLE
Replace Placeholder Text in Criteria Search Section

### ISSUE THREAD

**Issue by Shayan1375** [medizininformatik-initiative/feasibility-gui#208]
### Description
The Criteria Search section currently contains placeholder text ("Lorem ipsum dolor sit amet...") which needs to be replaced with relevant content. The placeholder text does not provide any useful information to the users and should be updated to accurately describe the purpose and functionality of this search feature.

![image](https://github.com/medizininformatik-initiative/feasibility-gui/assets/18329952/65f24423-8bd1-45c0-9072-a5a13843fd66)

### Desired Change:
Please provide appropriate text that explains the Criteria Search function, its importance, and how users can effectively use it. We need this text in both English and German.

**Comment by juliangruendner** [comment]
@kleinertp:

Suggestion english text:

Start typing and search for clinical cohort defining criteria. We currently support criteria from these general clinical contexts:
<List-of-Contexts-here   - e.g. Laboratory, Condition, Procedure, Specimen, etc. - potentially list all here - list could be long>
For further detailed information on the data currently available in our portal as well as the possible criteria, please refer to <link-to-fdpg-website-here>

**Comment by kleinertp** [comment]
@juliangruendner  so?
Sollte man hier schon mit aufnehmen dass im nächsten Schritt die auszuleitenden Datenpunkte separat identifiziert werden?

Search for clinical cohort criteria. Available Data Items are structured according to the Core Data Set. Common Codesystems are supported like ICD10, LOINC, OPS among others. Further general criteria such as age can be queried. Inclusion and exclusion criteria available being combined using AND/OR logical terms. Results may vary due to response times of sites as well as depending on technical availability of sites.
For further detailed information on availability or missing data items please contact info@
